# Common Command Line Option Defaults
CLEAR_CACHEDIR="yes"
SAVE_CONFIG="no"
BOOTLOADER="grub2"

# GENKERNEL LOCATION CONFIGURATION
GK_SHARE="${GK_SHARE:-/usr/share/genkernel}"
CACHE_DIR="/var/cache/genkernel"
DISTDIR="${GK_SHARE}/distfiles"
LOGFILE="/var/log/genkernel.log"
LOGLEVEL=1

# COMPILED UTILS CONFIGURATION
DEFAULT_KERNEL_SOURCE="/usr/src/linux"
DEFAULT_KERNEL_CONFIG="/etc/kernel/config"
